import 'package:flutter_test/flutter_test.dart';
import 'package:nahpu/services/database/database.dart';
import 'package:drift_dev/api/migrations_native.dart';
import 'generated_migrations/schema.dart';

void main() {
  late SchemaVerifier verifier;

  setUpAll(() {
    // GeneratedHelper() was generated by drift, the verifier is an api
    // provided by drift_dev.
    verifier = SchemaVerifier(GeneratedHelper());
  });

  for (final version in [6, 7, 8]) {
    test('upgrade from v$version to v9', () async {
      final connection = await verifier.startAt(version);
      final db = Database.forMigrationTesting(connection);

      await verifier.migrateAndValidate(db, 9);
      await db.close();
    });
  }
}
