import 'package:flutter_test/flutter_test.dart';
import 'package:drift/drift.dart' hide isNull;
import 'package:drift/native.dart';
import 'package:nahpu/services/database/database.dart';
import 'package:drift_dev/api/migrations_native.dart';
import 'generated_migrations/schema.dart';

void main() {
  late SchemaVerifier verifier;

  setUpAll(() {
    // GeneratedHelper() was generated by drift, the verifier is an api
    // provided by drift_dev.
    verifier = SchemaVerifier(GeneratedHelper());
  });

  for (final version in [6, 7, 8, 9, 10, 11, 12]) {
    test('upgrade from v$version to v13', () async {
      final connection = await verifier.startAt(version);
      final db = Database.forMigrationTesting(connection);

      await verifier.migrateAndValidate(db, 13);
      await db.close();
    });
  }

  test('repairs an existing v8 index during upgrade', () async {
    final schema = await verifier.schemaAt(8);
    schema.rawDatabase.execute(
      'CREATE INDEX site_project_idx ON site(projectUuid)',
    );
    final db = Database.forMigrationTesting(schema.newConnection());

    await verifier.migrateAndValidate(db, 13);
    await db.close();
  });

  test('repairs an outdated v9 index definition', () async {
    final schema = await verifier.schemaAt(9);
    schema.rawDatabase.execute('DROP INDEX site_project_idx');
    schema.rawDatabase.execute(
      'CREATE INDEX site_project_idx ON site(siteType)',
    );
    final db = Database.forMigrationTesting(schema.newConnection());

    await verifier.migrateAndValidate(db, 13);
    final columns = await db
        .customSelect(
          'PRAGMA index_info(site_project_idx)',
          readsFrom: const {},
        )
        .get();

    expect(columns.map((row) => row.data['name']), ['projectUuid']);
    await db.close();
  });

  test('v11 attribute-table renames preserve every stored column', () async {
    final schema = await verifier.schemaAt(10);
    final raw = schema.rawDatabase;
    raw.execute("INSERT INTO project (uuid, name) VALUES ('project', 'Test')");
    raw.execute(
      "INSERT INTO specimen (uuid, projectUuid) VALUES ('specimen', 'project')",
    );

    const legacyToCanonical = {
      'mammalMeasurement': 'mammalAttribute',
      'avianMeasurement': 'birdAttribute',
      'herpMeasurement': 'herpAttribute',
    };
    final expected = <String, Map<String, Object?>>{};
    for (final table in legacyToCanonical.keys) {
      final columns = raw.select('PRAGMA table_info("$table")');
      final names = columns.map((column) => column['name'] as String).toList();
      final values = <Object?>[];
      for (var index = 0; index < columns.length; index++) {
        final column = columns[index];
        final name = column['name'] as String;
        final type = (column['type'] as String).toUpperCase();
        values.add(switch ((name, type)) {
          ('specimenUuid', _) => 'specimen',
          (_, 'REAL') => index + 0.25,
          (_, 'INT') => index,
          _ => '$table-$name',
        });
      }
      final placeholders = List.filled(values.length, '?').join(', ');
      raw.execute(
        'INSERT INTO "$table" (${names.map((name) => '"$name"').join(', ')}) '
        'VALUES ($placeholders)',
        values,
      );
      expected[table] = Map<String, Object?>.from(
        raw.select('SELECT * FROM "$table"').single,
      );
    }

    final db = Database.forMigrationTesting(schema.newConnection());
    await verifier.migrateAndValidate(db, 13);

    for (final entry in legacyToCanonical.entries) {
      final actual = await db
          .customSelect('SELECT * FROM "${entry.value}"', readsFrom: const {})
          .getSingle();
      expect(actual.data, expected[entry.key]);
    }
    final tables = await db
        .customSelect(
          "SELECT name FROM sqlite_master WHERE type = 'table'",
          readsFrom: const {},
        )
        .get();
    final tableNames = tables.map((row) => row.data['name']).toSet();
    expect(tableNames, containsAll(legacyToCanonical.values));
    for (final legacyName in legacyToCanonical.keys) {
      expect(tableNames, isNot(contains(legacyName)));
    }

    final foreignKeyViolations = await db
        .customSelect('PRAGMA foreign_key_check', readsFrom: const {})
        .get();
    expect(foreignKeyViolations, isEmpty);
    final integrity = await db
        .customSelect('PRAGMA integrity_check', readsFrom: const {})
        .getSingle();
    expect(integrity.data.values.single, 'ok');
    await db.close();
  });

  test(
    'v13 moves legacy specimen associated data into the link table',
    () async {
      final schema = await verifier.schemaAt(11);
      final raw = schema.rawDatabase;
      raw.execute(
        "INSERT INTO project (uuid, name) VALUES ('project-a', 'Project A')",
      );
      raw.execute(
        "INSERT INTO project (uuid, name) VALUES ('project-b', 'Project B')",
      );
      raw.execute(
        "INSERT INTO specimen (uuid, projectUuid) "
        "VALUES ('specimen-a', 'project-a')",
      );
      raw.execute(
        "INSERT INTO site (siteID, projectUuid) "
        "VALUES ('Site A', 'project-a')",
      );
      raw.execute(
        "INSERT INTO site (siteID, projectUuid) "
        "VALUES ('Site B', 'project-b')",
      );
      raw.execute(
        "INSERT INTO associatedData "
        "(specimenUuid, name, type, date, description, url) "
        "VALUES ('specimen-a', 'Recording', 'File', '2026-07-26', "
        "'Call recording', 'call.wav')",
      );

      final db = Database.forMigrationTesting(schema.newConnection());
      await verifier.migrateAndValidate(db, 13);

      final data = await db.select(db.associatedData).getSingle();
      expect(data.projectUuid, 'project-a');
      expect(data.name, 'Recording');
      expect(data.uri, 'call.wav');

      final specimenLinks = await db.select(db.specimenAssociatedData).get();
      expect(specimenLinks, hasLength(1));
      expect(specimenLinks.single.specimenUuid, 'specimen-a');
      expect(specimenLinks.single.associatedDataId, data.primaryId);
      expect(await db.select(db.siteAssociatedData).get(), isEmpty);

      final sites = await db.select(db.site).get();
      expect(sites.map((site) => site.projectUuid), {'project-a', 'project-b'});
      await db.close();
    },
  );

  test('v12 to v13 preserves renamed tables, columns, and links', () async {
    final schema = await verifier.schemaAt(12);
    final raw = schema.rawDatabase;
    raw.execute(
      "INSERT INTO project (uuid, name) VALUES ('project-a', 'Project A')",
    );
    raw.execute(
      "INSERT INTO specimen (uuid, projectUuid) "
      "VALUES ('specimen-a', 'project-a')",
    );
    raw.execute(
      "INSERT INTO site (id, siteID, projectUuid) "
      "VALUES (7, 'Fossil locality', 'project-a')",
    );
    raw.execute(
      "INSERT INTO paleontologySite (siteID, formation) "
      "VALUES (7, 'Hell Creek')",
    );
    raw.execute(
      "INSERT INTO associatedData "
      "(primaryId, specimenUuid, projectUuid, name, url) "
      "VALUES (11, 'specimen-a', 'project-a', 'Audio', 'call.wav')",
    );
    raw.execute(
      "INSERT INTO media (primaryId, projectUuid, fileName) "
      "VALUES (13, 'project-a', 'photo.jpg')",
    );
    raw.execute(
      "INSERT INTO customFieldDefinition (id, name) VALUES (17, 'Mass')",
    );
    raw.execute(
      "INSERT INTO customFieldValue "
      "(id, fieldDefinitionId, projectUuid, value) "
      "VALUES (19, 17, 'project-a', '2.5')",
    );

    final db = Database.forMigrationTesting(schema.newConnection());
    await verifier.migrateAndValidate(db, 13);

    final fossilSite = await db.select(db.fossilSite).getSingle();
    expect(fossilSite.siteID, 7);
    expect(fossilSite.formation, 'Hell Creek');
    expect((await db.select(db.associatedData).getSingle()).uri, 'call.wav');
    expect((await db.select(db.media).getSingle()).uri, isNull);
    expect((await db.select(db.customFieldValue).getSingle()).unit, isNull);

    final links = await db.select(db.specimenAssociatedData).get();
    expect(links, hasLength(1));
    expect(links.single.specimenUuid, 'specimen-a');
    expect(links.single.associatedDataId, 11);

    final tables = await db
        .customSelect(
          "SELECT name FROM sqlite_master WHERE type = 'table'",
          readsFrom: const {},
        )
        .get();
    final tableNames = tables.map((row) => row.read<String>('name')).toSet();
    expect(tableNames, contains('fossilSite'));
    expect(tableNames, isNot(contains('paleontologySite')));

    final associatedColumns = await db
        .customSelect('PRAGMA table_info(associatedData)', readsFrom: const {})
        .get();
    final columnNames = associatedColumns
        .map((row) => row.read<String>('name'))
        .toSet();
    expect(columnNames, contains('uri'));
    expect(columnNames, isNot(contains('url')));
    expect(columnNames, isNot(contains('specimenUuid')));

    final associatedDataTriggers = await db
        .customSelect(
          "SELECT name FROM sqlite_master "
          "WHERE type = 'trigger' AND tbl_name = 'associatedData'",
          readsFrom: const {},
        )
        .get();
    expect(associatedDataTriggers, isEmpty);
    await db.close();
  });

  test('v13 associated data links enforce project ownership', () async {
    final db = Database.forTesting(DatabaseConnection(NativeDatabase.memory()));
    await db
        .into(db.project)
        .insert(
          const ProjectCompanion(
            uuid: Value('project-a'),
            name: Value('Project A'),
          ),
        );
    await db
        .into(db.project)
        .insert(
          const ProjectCompanion(
            uuid: Value('project-b'),
            name: Value('Project B'),
          ),
        );
    await db
        .into(db.specimen)
        .insert(
          const SpecimenCompanion(
            uuid: Value('specimen-a'),
            projectUuid: Value('project-a'),
          ),
        );
    final siteA = await db
        .into(db.site)
        .insert(const SiteCompanion(projectUuid: Value('project-a')));
    final siteB = await db
        .into(db.site)
        .insert(const SiteCompanion(projectUuid: Value('project-b')));
    final dataId = await db
        .into(db.associatedData)
        .insert(const AssociatedDataCompanion(projectUuid: Value('project-a')));

    await db
        .into(db.specimenAssociatedData)
        .insert(
          SpecimenAssociatedDataCompanion.insert(
            specimenUuid: 'specimen-a',
            associatedDataId: dataId,
          ),
        );
    await db
        .into(db.siteAssociatedData)
        .insert(
          SiteAssociatedDataCompanion.insert(
            siteId: siteA,
            associatedDataId: dataId,
          ),
        );
    await expectLater(
      db
          .into(db.siteAssociatedData)
          .insert(
            SiteAssociatedDataCompanion.insert(
              siteId: siteB,
              associatedDataId: dataId,
            ),
          ),
      throwsA(anything),
    );
    await db.close();
  });
}
