import 'dart:io';

import 'package:file_selector/file_selector.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:geolocator/geolocator.dart';
import 'package:nahpu/screens/shared/forms/fields.dart';
import 'package:nahpu/screens/shared/layout/layout.dart';
import 'package:nahpu/screens/shared/maps/coordinate_location_map.dart';
import 'package:nahpu/screens/shared/maps/full_screen_map_page.dart';
import 'package:nahpu/screens/settings/map_settings.dart';
import 'package:nahpu/screens/shared/media/qr.dart';
import 'package:nahpu/services/record_exchange/coordinate_exchange_service.dart';
import 'package:nahpu/services/coordinate_input.dart';
import 'package:nahpu/services/controlled_vocabulary_services.dart';
import 'package:nahpu/services/io_services.dart';
import 'package:nahpu/services/types/controllers.dart';
import 'package:nahpu/services/maps/coordinate_map_point.dart';
import 'package:nahpu/services/providers/sites.dart';
import 'package:nahpu/services/providers/settings.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:nahpu/screens/shared/actions/buttons.dart';
import 'package:nahpu/screens/shared/actions/export_share_button.dart';
import 'package:nahpu/screens/exports/components/file_settings.dart';
import 'package:nahpu/screens/shared/forms/forms.dart';
import 'package:nahpu/screens/shared/common/common.dart';
import 'package:nahpu/services/database/database.dart';
import 'package:drift/drift.dart' as db;
import 'package:nahpu/services/site_services.dart';
import 'package:nahpu/services/types/sites.dart';
import 'package:nahpu/services/utility_services.dart';
import 'package:nahpu/src/rust/api/gis.dart';
import 'package:nahpu/src/rust/api/gis.dart' as rust_gis;
import 'package:nahpu/styles/design_tokens.dart';
import 'package:url_launcher/url_launcher.dart';

part 'coordinates/coordinate_list.dart';
part 'coordinates/coordinate_details.dart';
part 'coordinates/coordinate_editor.dart';
part 'coordinates/coordinate_manager.dart';
