import 'dart:io';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';

/// Guards the icon font against the one failure it cannot signal at runtime.
///
/// `nahpu_icons.dart` and `nahpu_font.ttf` are both generated by
/// https://github.com/nahpu/nahpu-icon-generator, and codepoints there are
/// assigned in alphabetical filename order. Adding or removing an icon
/// renumbers everything after it, so a font that is one build out of step with
/// its Dart class does not throw -- it silently draws the wrong animal. These
/// tests fail instead.
const String fontPath = 'assets/fonts/nahpu_font.ttf';
const String dartPath = 'lib/services/types/nahpu_icons.dart';
const String pubspecPath = 'pubspec.yaml';

void main() {
  group('Icon font and its Dart class stay in sync', () {
    test('every declared codepoint exists in the font', () {
      final declared = declaredIcons();
      final inFont = fontCodepoints();

      expect(declared, isNotEmpty, reason: '$dartPath declares no icons');

      final missing = declared.entries
          .where((e) => !inFont.contains(e.value))
          .map((e) => '${e.key} -> ${asHex(e.value)}')
          .toList();

      expect(
        missing,
        isEmpty,
        reason:
            'These constants have no glyph in $fontPath. The font is stale, or '
            'the Dart class is. Regenerate both together:\n'
            '${missing.join('\n')}',
      );
    });

    test('the font has no glyphs the Dart class omits', () {
      final declared = declaredIcons().values.toSet();
      final orphans = fontCodepoints().difference(declared).map(asHex).toList()
        ..sort();

      expect(
        orphans,
        isEmpty,
        reason:
            'The font ships glyphs that $dartPath does not expose, so the Dart '
            'class is older than the font:\n${orphans.join(', ')}',
      );
    });

    test('codepoints are unique and sit in the Private Use Area', () {
      final declared = declaredIcons();
      final seen = <int, String>{};
      final problems = <String>[];

      for (final entry in declared.entries) {
        final clash = seen[entry.value];
        if (clash != null) {
          problems.add(
            '${entry.key} collides with $clash at ${asHex(entry.value)}',
          );
        } else {
          seen[entry.value] = entry.key;
        }
        if (entry.value < 0xE000 || entry.value > 0xF8FF) {
          problems.add(
            '${entry.key} at ${asHex(entry.value)} is outside the PUA',
          );
        }
      }

      expect(problems, isEmpty, reason: problems.join('\n'));
    });

    test('the font family matches the one registered in pubspec', () {
      final dartSource = File(dartPath).readAsStringSync();
      final family = RegExp(
        r"_fontFamily\s*=\s*'([^']+)'",
      ).firstMatch(dartSource)?.group(1);

      expect(family, isNotNull, reason: 'no _fontFamily found in $dartPath');

      final pubspec = File(pubspecPath).readAsStringSync();
      final registered = RegExp(
        'family:\\s*"?${RegExp.escape(family!)}"?\\s*\$',
        multiLine: true,
      );
      expect(
        registered.hasMatch(pubspec),
        isTrue,
        reason:
            '$dartPath uses "$family" but pubspec.yaml does not register it',
      );
      expect(
        pubspec.contains(fontPath),
        isTrue,
        reason: 'pubspec.yaml does not bundle $fontPath',
      );
    });
  });
}

String asHex(int codepoint) =>
    'U+${codepoint.toRadixString(16).toUpperCase().padLeft(4, '0')}';

/// Constant name -> codepoint, read straight out of the generated source.
///
/// Dart has no runtime reflection here, so the source is parsed instead. This
/// is the same approach `icon_asset_test.dart` takes for asset path literals.
Map<String, int> declaredIcons() {
  final source = File(dartPath).readAsStringSync();
  final pattern = RegExp(
    r'static const IconData (\w+)\s*=\s*IconData\(\s*0x([0-9a-fA-F]+)',
  );

  return {
    for (final match in pattern.allMatches(source))
      match.group(1)!: int.parse(match.group(2)!, radix: 16),
  };
}

/// Every codepoint the font's `cmap` maps to a glyph.
Set<int> fontCodepoints() {
  final bytes = ByteData.sublistView(File(fontPath).readAsBytesSync());
  final cmap = _findTable(bytes, 'cmap');
  expect(cmap, isNotNull, reason: '$fontPath has no cmap table');
  return _parseCmap(bytes, cmap!);
}

/// Offset of a named table in the font's table directory, or null.
int? _findTable(ByteData bytes, String tag) {
  final numTables = bytes.getUint16(4);
  for (var i = 0; i < numTables; i++) {
    final record = 12 + i * 16;
    final name = String.fromCharCodes(
      List.generate(4, (j) => bytes.getUint8(record + j)),
    );
    if (name == tag) return bytes.getUint32(record + 8);
  }
  return null;
}

Set<int> _parseCmap(ByteData bytes, int cmapOffset) {
  final numSubtables = bytes.getUint16(cmapOffset + 2);
  final codepoints = <int>{};
  final formats = <int>{};

  for (var i = 0; i < numSubtables; i++) {
    final record = cmapOffset + 4 + i * 8;
    final subtable = cmapOffset + bytes.getUint32(record + 4);
    final format = bytes.getUint16(subtable);
    formats.add(format);
    if (format == 4) codepoints.addAll(_parseFormat4(bytes, subtable));
  }

  // Every icon codepoint is in the BMP, so format 4 is all the generator emits.
  // Assert it rather than assume it, so a generator change fails here loudly
  // instead of silently reporting an empty codepoint set.
  expect(
    formats.contains(4),
    isTrue,
    reason:
        'No cmap format 4 subtable in $fontPath (found formats $formats). '
        'This parser only understands format 4 -- extend it.',
  );

  return codepoints;
}

Set<int> _parseFormat4(ByteData bytes, int subtable) {
  final segCountX2 = bytes.getUint16(subtable + 6);
  final segCount = segCountX2 ~/ 2;

  final endCodes = subtable + 14;
  final startCodes = endCodes + segCountX2 + 2;
  final idDeltas = startCodes + segCountX2;
  final idRangeOffsets = idDeltas + segCountX2;

  final codepoints = <int>{};

  for (var seg = 0; seg < segCount; seg++) {
    final end = bytes.getUint16(endCodes + seg * 2);
    final start = bytes.getUint16(startCodes + seg * 2);
    if (start > end || start == 0xFFFF) continue;

    final delta = bytes.getInt16(idDeltas + seg * 2);
    final rangeOffsetAddress = idRangeOffsets + seg * 2;
    final rangeOffset = bytes.getUint16(rangeOffsetAddress);

    for (var code = start; code <= end; code++) {
      int glyphId;
      if (rangeOffset == 0) {
        glyphId = (code + delta) & 0xFFFF;
      } else {
        final glyphAddress =
            rangeOffsetAddress + rangeOffset + (code - start) * 2;
        glyphId = bytes.getUint16(glyphAddress);
        if (glyphId != 0) glyphId = (glyphId + delta) & 0xFFFF;
      }
      if (glyphId != 0) codepoints.add(code);
    }
  }

  return codepoints;
}
