// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/archive.dart';
import 'api/common.dart';
import 'api/config.dart';
import 'api/export.dart';
import 'api/gis.dart';
import 'api/import.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiCommonInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1295134116;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'rust_lib_nahpu',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiCommonCheckRust();

  Future<Uint8List> crateApiExportCompileTypstToPdf(
      {required String typstContent, required List<Uint8List> fontBytes});

  Future<DdmCoordinateFfi> crateApiGisDdToDdm(
      {required double dd, required bool isLatitude});

  Future<DmsCoordinateFfi> crateApiGisDdToDms(
      {required double dd, required bool isLatitude});

  Future<UtmCoordinateFfi> crateApiGisDdToUtm(
      {required double latitude, required double longitude});

  Future<double> crateApiGisDdmToDd(
      {required int degrees,
      required double minutes,
      required CardinalDirection direction});

  Future<void> crateApiConfigDeleteDocumentPreset({required String name});

  Future<void> crateApiConfigDeleteUserConfig({required String key});

  Future<double> crateApiGisDmsToDd(
      {required int degrees,
      required int minutes,
      required double seconds,
      required CardinalDirection direction});

  Future<void> crateApiExportExportCoordinates(
      {required String jsonContent,
      required String outputPath,
      required String exportFormat});

  Future<Uint8List> crateApiExportGenerateDocument(
      {required String jsonContent,
      required String exportFormat,
      required List<Uint8List> fontBytes});

  Future<List<ConfigPresetEntry>> crateApiConfigGetAllDocumentPresets();

  Future<ConfigExportPreset?> crateApiConfigGetDocumentPreset(
      {required String name});

  Future<List<String>?> crateApiConfigGetUserConfigList({required String key});

  Future<String?> crateApiConfigGetUserConfigString({required String key});

  Future<void> crateApiCommonInitApp();

  Future<void> crateApiConfigInitConfigDb({required String path});

  Future<double> crateApiGisParseCoordinateString({required String s});

  Future<List<String>> crateApiImportRecordReaderGetExcelSheetNames(
      {required RecordReader that});

  Future<List<List<String>>> crateApiImportRecordReaderImportDelimitedRaw(
      {required RecordReader that, required String delimiter});

  Future<List<List<String>>> crateApiImportRecordReaderImportExcelRaw(
      {required RecordReader that, required String sheetName});

  Future<RecordReader> crateApiImportRecordReaderNew(
      {required String filePath});

  Future<RecordWriter> crateApiExportRecordWriterNew(
      {required String jsonContent,
      required String outputPath,
      required List<String> columnNames,
      required String exportFormat,
      required bool concatenateMultiEntries});

  Future<void> crateApiExportRecordWriterWrite({required RecordWriter that});

  Future<void> crateApiConfigSetDocumentPreset(
      {required String name, required ConfigExportPreset preset});

  Future<void> crateApiConfigSetUserConfigList(
      {required String key, required List<String> value});

  Future<void> crateApiConfigSetUserConfigString(
      {required String key, required String value});

  Future<(double, double)> crateApiGisUtmToDd(
      {required int zone,
      required CardinalDirection hemisphere,
      required double easting,
      required double northing});

  Future<void> crateApiArchiveZipExtractorExtract({required ZipExtractor that});

  Future<ZipExtractor> crateApiArchiveZipExtractorNew(
      {required String archivePath, required String outputDir});

  Future<ZipWriter> crateApiArchiveZipWriterNew(
      {required String parentDir,
      required List<String> files,
      required String outputPath});

  Future<void> crateApiArchiveZipWriterWrite({required ZipWriter that});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiCommonCheckRust() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCommonCheckRustConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCommonCheckRustConstMeta => const TaskConstMeta(
        debugName: "check_rust",
        argNames: [],
      );

  @override
  Future<Uint8List> crateApiExportCompileTypstToPdf(
      {required String typstContent, required List<Uint8List> fontBytes}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(typstContent, serializer);
        sse_encode_list_list_prim_u_8_strict(fontBytes, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiExportCompileTypstToPdfConstMeta,
      argValues: [typstContent, fontBytes],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiExportCompileTypstToPdfConstMeta =>
      const TaskConstMeta(
        debugName: "compile_typst_to_pdf",
        argNames: ["typstContent", "fontBytes"],
      );

  @override
  Future<DdmCoordinateFfi> crateApiGisDdToDdm(
      {required double dd, required bool isLatitude}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_f_64(dd, serializer);
        sse_encode_bool(isLatitude, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_ddm_coordinate_ffi,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGisDdToDdmConstMeta,
      argValues: [dd, isLatitude],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGisDdToDdmConstMeta => const TaskConstMeta(
        debugName: "dd_to_ddm",
        argNames: ["dd", "isLatitude"],
      );

  @override
  Future<DmsCoordinateFfi> crateApiGisDdToDms(
      {required double dd, required bool isLatitude}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_f_64(dd, serializer);
        sse_encode_bool(isLatitude, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_dms_coordinate_ffi,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGisDdToDmsConstMeta,
      argValues: [dd, isLatitude],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGisDdToDmsConstMeta => const TaskConstMeta(
        debugName: "dd_to_dms",
        argNames: ["dd", "isLatitude"],
      );

  @override
  Future<UtmCoordinateFfi> crateApiGisDdToUtm(
      {required double latitude, required double longitude}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_f_64(latitude, serializer);
        sse_encode_f_64(longitude, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_utm_coordinate_ffi,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGisDdToUtmConstMeta,
      argValues: [latitude, longitude],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGisDdToUtmConstMeta => const TaskConstMeta(
        debugName: "dd_to_utm",
        argNames: ["latitude", "longitude"],
      );

  @override
  Future<double> crateApiGisDdmToDd(
      {required int degrees,
      required double minutes,
      required CardinalDirection direction}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_u_32(degrees, serializer);
        sse_encode_f_64(minutes, serializer);
        sse_encode_cardinal_direction(direction, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_f_64,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGisDdmToDdConstMeta,
      argValues: [degrees, minutes, direction],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGisDdmToDdConstMeta => const TaskConstMeta(
        debugName: "ddm_to_dd",
        argNames: ["degrees", "minutes", "direction"],
      );

  @override
  Future<void> crateApiConfigDeleteDocumentPreset({required String name}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiConfigDeleteDocumentPresetConstMeta,
      argValues: [name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiConfigDeleteDocumentPresetConstMeta =>
      const TaskConstMeta(
        debugName: "delete_document_preset",
        argNames: ["name"],
      );

  @override
  Future<void> crateApiConfigDeleteUserConfig({required String key}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(key, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiConfigDeleteUserConfigConstMeta,
      argValues: [key],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiConfigDeleteUserConfigConstMeta =>
      const TaskConstMeta(
        debugName: "delete_user_config",
        argNames: ["key"],
      );

  @override
  Future<double> crateApiGisDmsToDd(
      {required int degrees,
      required int minutes,
      required double seconds,
      required CardinalDirection direction}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_u_32(degrees, serializer);
        sse_encode_u_32(minutes, serializer);
        sse_encode_f_64(seconds, serializer);
        sse_encode_cardinal_direction(direction, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_f_64,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGisDmsToDdConstMeta,
      argValues: [degrees, minutes, seconds, direction],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGisDmsToDdConstMeta => const TaskConstMeta(
        debugName: "dms_to_dd",
        argNames: ["degrees", "minutes", "seconds", "direction"],
      );

  @override
  Future<void> crateApiExportExportCoordinates(
      {required String jsonContent,
      required String outputPath,
      required String exportFormat}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(jsonContent, serializer);
        sse_encode_String(outputPath, serializer);
        sse_encode_String(exportFormat, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiExportExportCoordinatesConstMeta,
      argValues: [jsonContent, outputPath, exportFormat],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiExportExportCoordinatesConstMeta =>
      const TaskConstMeta(
        debugName: "export_coordinates",
        argNames: ["jsonContent", "outputPath", "exportFormat"],
      );

  @override
  Future<Uint8List> crateApiExportGenerateDocument(
      {required String jsonContent,
      required String exportFormat,
      required List<Uint8List> fontBytes}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(jsonContent, serializer);
        sse_encode_String(exportFormat, serializer);
        sse_encode_list_list_prim_u_8_strict(fontBytes, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiExportGenerateDocumentConstMeta,
      argValues: [jsonContent, exportFormat, fontBytes],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiExportGenerateDocumentConstMeta =>
      const TaskConstMeta(
        debugName: "generate_document",
        argNames: ["jsonContent", "exportFormat", "fontBytes"],
      );

  @override
  Future<List<ConfigPresetEntry>> crateApiConfigGetAllDocumentPresets() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_config_preset_entry,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiConfigGetAllDocumentPresetsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiConfigGetAllDocumentPresetsConstMeta =>
      const TaskConstMeta(
        debugName: "get_all_document_presets",
        argNames: [],
      );

  @override
  Future<ConfigExportPreset?> crateApiConfigGetDocumentPreset(
      {required String name}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_config_export_preset,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiConfigGetDocumentPresetConstMeta,
      argValues: [name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiConfigGetDocumentPresetConstMeta =>
      const TaskConstMeta(
        debugName: "get_document_preset",
        argNames: ["name"],
      );

  @override
  Future<List<String>?> crateApiConfigGetUserConfigList({required String key}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(key, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_list_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiConfigGetUserConfigListConstMeta,
      argValues: [key],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiConfigGetUserConfigListConstMeta =>
      const TaskConstMeta(
        debugName: "get_user_config_list",
        argNames: ["key"],
      );

  @override
  Future<String?> crateApiConfigGetUserConfigString({required String key}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(key, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiConfigGetUserConfigStringConstMeta,
      argValues: [key],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiConfigGetUserConfigStringConstMeta =>
      const TaskConstMeta(
        debugName: "get_user_config_string",
        argNames: ["key"],
      );

  @override
  Future<void> crateApiCommonInitApp() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCommonInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCommonInitAppConstMeta => const TaskConstMeta(
        debugName: "init_app",
        argNames: [],
      );

  @override
  Future<void> crateApiConfigInitConfigDb({required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiConfigInitConfigDbConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiConfigInitConfigDbConstMeta => const TaskConstMeta(
        debugName: "init_config_db",
        argNames: ["path"],
      );

  @override
  Future<double> crateApiGisParseCoordinateString({required String s}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(s, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 18, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_f_64,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGisParseCoordinateStringConstMeta,
      argValues: [s],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGisParseCoordinateStringConstMeta =>
      const TaskConstMeta(
        debugName: "parse_coordinate_string",
        argNames: ["s"],
      );

  @override
  Future<List<String>> crateApiImportRecordReaderGetExcelSheetNames(
      {required RecordReader that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_record_reader(that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 19, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiImportRecordReaderGetExcelSheetNamesConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiImportRecordReaderGetExcelSheetNamesConstMeta =>
      const TaskConstMeta(
        debugName: "record_reader_get_excel_sheet_names",
        argNames: ["that"],
      );

  @override
  Future<List<List<String>>> crateApiImportRecordReaderImportDelimitedRaw(
      {required RecordReader that, required String delimiter}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_record_reader(that, serializer);
        sse_encode_String(delimiter, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 20, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_list_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiImportRecordReaderImportDelimitedRawConstMeta,
      argValues: [that, delimiter],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiImportRecordReaderImportDelimitedRawConstMeta =>
      const TaskConstMeta(
        debugName: "record_reader_import_delimited_raw",
        argNames: ["that", "delimiter"],
      );

  @override
  Future<List<List<String>>> crateApiImportRecordReaderImportExcelRaw(
      {required RecordReader that, required String sheetName}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_record_reader(that, serializer);
        sse_encode_String(sheetName, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 21, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_list_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiImportRecordReaderImportExcelRawConstMeta,
      argValues: [that, sheetName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiImportRecordReaderImportExcelRawConstMeta =>
      const TaskConstMeta(
        debugName: "record_reader_import_excel_raw",
        argNames: ["that", "sheetName"],
      );

  @override
  Future<RecordReader> crateApiImportRecordReaderNew(
      {required String filePath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(filePath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 22, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_record_reader,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiImportRecordReaderNewConstMeta,
      argValues: [filePath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiImportRecordReaderNewConstMeta =>
      const TaskConstMeta(
        debugName: "record_reader_new",
        argNames: ["filePath"],
      );

  @override
  Future<RecordWriter> crateApiExportRecordWriterNew(
      {required String jsonContent,
      required String outputPath,
      required List<String> columnNames,
      required String exportFormat,
      required bool concatenateMultiEntries}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(jsonContent, serializer);
        sse_encode_String(outputPath, serializer);
        sse_encode_list_String(columnNames, serializer);
        sse_encode_String(exportFormat, serializer);
        sse_encode_bool(concatenateMultiEntries, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 23, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_record_writer,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiExportRecordWriterNewConstMeta,
      argValues: [
        jsonContent,
        outputPath,
        columnNames,
        exportFormat,
        concatenateMultiEntries
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiExportRecordWriterNewConstMeta =>
      const TaskConstMeta(
        debugName: "record_writer_new",
        argNames: [
          "jsonContent",
          "outputPath",
          "columnNames",
          "exportFormat",
          "concatenateMultiEntries"
        ],
      );

  @override
  Future<void> crateApiExportRecordWriterWrite({required RecordWriter that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_record_writer(that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 24, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiExportRecordWriterWriteConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiExportRecordWriterWriteConstMeta =>
      const TaskConstMeta(
        debugName: "record_writer_write",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiConfigSetDocumentPreset(
      {required String name, required ConfigExportPreset preset}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        sse_encode_box_autoadd_config_export_preset(preset, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 25, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiConfigSetDocumentPresetConstMeta,
      argValues: [name, preset],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiConfigSetDocumentPresetConstMeta =>
      const TaskConstMeta(
        debugName: "set_document_preset",
        argNames: ["name", "preset"],
      );

  @override
  Future<void> crateApiConfigSetUserConfigList(
      {required String key, required List<String> value}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(key, serializer);
        sse_encode_list_String(value, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 26, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiConfigSetUserConfigListConstMeta,
      argValues: [key, value],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiConfigSetUserConfigListConstMeta =>
      const TaskConstMeta(
        debugName: "set_user_config_list",
        argNames: ["key", "value"],
      );

  @override
  Future<void> crateApiConfigSetUserConfigString(
      {required String key, required String value}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(key, serializer);
        sse_encode_String(value, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 27, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiConfigSetUserConfigStringConstMeta,
      argValues: [key, value],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiConfigSetUserConfigStringConstMeta =>
      const TaskConstMeta(
        debugName: "set_user_config_string",
        argNames: ["key", "value"],
      );

  @override
  Future<(double, double)> crateApiGisUtmToDd(
      {required int zone,
      required CardinalDirection hemisphere,
      required double easting,
      required double northing}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_u_8(zone, serializer);
        sse_encode_cardinal_direction(hemisphere, serializer);
        sse_encode_f_64(easting, serializer);
        sse_encode_f_64(northing, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 28, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_record_f_64_f_64,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGisUtmToDdConstMeta,
      argValues: [zone, hemisphere, easting, northing],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGisUtmToDdConstMeta => const TaskConstMeta(
        debugName: "utm_to_dd",
        argNames: ["zone", "hemisphere", "easting", "northing"],
      );

  @override
  Future<void> crateApiArchiveZipExtractorExtract(
      {required ZipExtractor that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_zip_extractor(that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 29, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiArchiveZipExtractorExtractConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiArchiveZipExtractorExtractConstMeta =>
      const TaskConstMeta(
        debugName: "zip_extractor_extract",
        argNames: ["that"],
      );

  @override
  Future<ZipExtractor> crateApiArchiveZipExtractorNew(
      {required String archivePath, required String outputDir}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(archivePath, serializer);
        sse_encode_String(outputDir, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 30, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_zip_extractor,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiArchiveZipExtractorNewConstMeta,
      argValues: [archivePath, outputDir],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiArchiveZipExtractorNewConstMeta =>
      const TaskConstMeta(
        debugName: "zip_extractor_new",
        argNames: ["archivePath", "outputDir"],
      );

  @override
  Future<ZipWriter> crateApiArchiveZipWriterNew(
      {required String parentDir,
      required List<String> files,
      required String outputPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(parentDir, serializer);
        sse_encode_list_String(files, serializer);
        sse_encode_String(outputPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 31, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_zip_writer,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiArchiveZipWriterNewConstMeta,
      argValues: [parentDir, files, outputPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiArchiveZipWriterNewConstMeta =>
      const TaskConstMeta(
        debugName: "zip_writer_new",
        argNames: ["parentDir", "files", "outputPath"],
      );

  @override
  Future<void> crateApiArchiveZipWriterWrite({required ZipWriter that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_zip_writer(that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 32, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiArchiveZipWriterWriteConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiArchiveZipWriterWriteConstMeta =>
      const TaskConstMeta(
        debugName: "zip_writer_write",
        argNames: ["that"],
      );

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Map.fromEntries(dco_decode_list_record_string_string(raw)
        .map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ConfigExportPreset dco_decode_box_autoadd_config_export_preset(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_config_export_preset(raw);
  }

  @protected
  RecordReader dco_decode_box_autoadd_record_reader(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_record_reader(raw);
  }

  @protected
  RecordWriter dco_decode_box_autoadd_record_writer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_record_writer(raw);
  }

  @protected
  ZipExtractor dco_decode_box_autoadd_zip_extractor(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_zip_extractor(raw);
  }

  @protected
  ZipWriter dco_decode_box_autoadd_zip_writer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_zip_writer(raw);
  }

  @protected
  CardinalDirection dco_decode_cardinal_direction(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CardinalDirection.values[raw as int];
  }

  @protected
  ConfigCombinedField dco_decode_config_combined_field(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ConfigCombinedField(
      fieldId: dco_decode_String(arr[0]),
      fields: dco_decode_list_String(arr[1]),
    );
  }

  @protected
  ConfigExportPreset dco_decode_config_export_preset(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ConfigExportPreset(
      fields: dco_decode_Map_String_String_None(arr[0]),
      combinedFields: dco_decode_list_config_combined_field(arr[1]),
    );
  }

  @protected
  ConfigPresetEntry dco_decode_config_preset_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ConfigPresetEntry(
      name: dco_decode_String(arr[0]),
      preset: dco_decode_config_export_preset(arr[1]),
    );
  }

  @protected
  DdmCoordinateFfi dco_decode_ddm_coordinate_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DdmCoordinateFfi(
      degrees: dco_decode_u_32(arr[0]),
      minutes: dco_decode_f_64(arr[1]),
      direction: dco_decode_cardinal_direction(arr[2]),
    );
  }

  @protected
  DmsCoordinateFfi dco_decode_dms_coordinate_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return DmsCoordinateFfi(
      degrees: dco_decode_u_32(arr[0]),
      minutes: dco_decode_u_32(arr[1]),
      seconds: dco_decode_f_64(arr[2]),
      direction: dco_decode_cardinal_direction(arr[3]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ConfigCombinedField> dco_decode_list_config_combined_field(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_config_combined_field)
        .toList();
  }

  @protected
  List<ConfigPresetEntry> dco_decode_list_config_preset_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_config_preset_entry).toList();
  }

  @protected
  List<List<String>> dco_decode_list_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_String).toList();
  }

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_prim_u_8_strict).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_string).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  ConfigExportPreset? dco_decode_opt_box_autoadd_config_export_preset(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_config_export_preset(raw);
  }

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_String(raw);
  }

  @protected
  (double, double) dco_decode_record_f_64_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_f_64(arr[0]),
      dco_decode_f_64(arr[1]),
    );
  }

  @protected
  RecordReader dco_decode_record_reader(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return RecordReader(
      filePath: dco_decode_String(arr[0]),
    );
  }

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_String(arr[0]),
      dco_decode_String(arr[1]),
    );
  }

  @protected
  RecordWriter dco_decode_record_writer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return RecordWriter(
      jsonContent: dco_decode_String(arr[0]),
      outputPath: dco_decode_String(arr[1]),
      columnNames: dco_decode_list_String(arr[2]),
      exportFormat: dco_decode_String(arr[3]),
      concatenateMultiEntries: dco_decode_bool(arr[4]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  UtmCoordinateFfi dco_decode_utm_coordinate_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return UtmCoordinateFfi(
      zone: dco_decode_u_8(arr[0]),
      hemisphere: dco_decode_cardinal_direction(arr[1]),
      easting: dco_decode_f_64(arr[2]),
      northing: dco_decode_f_64(arr[3]),
    );
  }

  @protected
  ZipExtractor dco_decode_zip_extractor(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ZipExtractor(
      archivePath: dco_decode_String(arr[0]),
      outputDir: dco_decode_String(arr[1]),
    );
  }

  @protected
  ZipWriter dco_decode_zip_writer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ZipWriter(
      parentDir: dco_decode_String(arr[0]),
      altParentDir: dco_decode_opt_String(arr[1]),
      files: dco_decode_list_String(arr[2]),
      outputPath: dco_decode_String(arr[3]),
    );
  }

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_record_string_string(deserializer);
    return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ConfigExportPreset sse_decode_box_autoadd_config_export_preset(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_config_export_preset(deserializer));
  }

  @protected
  RecordReader sse_decode_box_autoadd_record_reader(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_record_reader(deserializer));
  }

  @protected
  RecordWriter sse_decode_box_autoadd_record_writer(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_record_writer(deserializer));
  }

  @protected
  ZipExtractor sse_decode_box_autoadd_zip_extractor(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_zip_extractor(deserializer));
  }

  @protected
  ZipWriter sse_decode_box_autoadd_zip_writer(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_zip_writer(deserializer));
  }

  @protected
  CardinalDirection sse_decode_cardinal_direction(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return CardinalDirection.values[inner];
  }

  @protected
  ConfigCombinedField sse_decode_config_combined_field(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_fieldId = sse_decode_String(deserializer);
    var var_fields = sse_decode_list_String(deserializer);
    return ConfigCombinedField(fieldId: var_fieldId, fields: var_fields);
  }

  @protected
  ConfigExportPreset sse_decode_config_export_preset(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_fields = sse_decode_Map_String_String_None(deserializer);
    var var_combinedFields =
        sse_decode_list_config_combined_field(deserializer);
    return ConfigExportPreset(
        fields: var_fields, combinedFields: var_combinedFields);
  }

  @protected
  ConfigPresetEntry sse_decode_config_preset_entry(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_preset = sse_decode_config_export_preset(deserializer);
    return ConfigPresetEntry(name: var_name, preset: var_preset);
  }

  @protected
  DdmCoordinateFfi sse_decode_ddm_coordinate_ffi(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_degrees = sse_decode_u_32(deserializer);
    var var_minutes = sse_decode_f_64(deserializer);
    var var_direction = sse_decode_cardinal_direction(deserializer);
    return DdmCoordinateFfi(
        degrees: var_degrees, minutes: var_minutes, direction: var_direction);
  }

  @protected
  DmsCoordinateFfi sse_decode_dms_coordinate_ffi(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_degrees = sse_decode_u_32(deserializer);
    var var_minutes = sse_decode_u_32(deserializer);
    var var_seconds = sse_decode_f_64(deserializer);
    var var_direction = sse_decode_cardinal_direction(deserializer);
    return DmsCoordinateFfi(
        degrees: var_degrees,
        minutes: var_minutes,
        seconds: var_seconds,
        direction: var_direction);
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ConfigCombinedField> sse_decode_list_config_combined_field(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ConfigCombinedField>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_config_combined_field(deserializer));
    }
    return ans_;
  }

  @protected
  List<ConfigPresetEntry> sse_decode_list_config_preset_entry(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ConfigPresetEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_config_preset_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<List<String>> sse_decode_list_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <List<String>>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Uint8List>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_prim_u_8_strict(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, String)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_string(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ConfigExportPreset? sse_decode_opt_box_autoadd_config_export_preset(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_config_export_preset(deserializer));
    } else {
      return null;
    }
  }

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (double, double) sse_decode_record_f_64_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_f_64(deserializer);
    var var_field1 = sse_decode_f_64(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  RecordReader sse_decode_record_reader(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_filePath = sse_decode_String(deserializer);
    return RecordReader(filePath: var_filePath);
  }

  @protected
  (String, String) sse_decode_record_string_string(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  RecordWriter sse_decode_record_writer(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_jsonContent = sse_decode_String(deserializer);
    var var_outputPath = sse_decode_String(deserializer);
    var var_columnNames = sse_decode_list_String(deserializer);
    var var_exportFormat = sse_decode_String(deserializer);
    var var_concatenateMultiEntries = sse_decode_bool(deserializer);
    return RecordWriter(
        jsonContent: var_jsonContent,
        outputPath: var_outputPath,
        columnNames: var_columnNames,
        exportFormat: var_exportFormat,
        concatenateMultiEntries: var_concatenateMultiEntries);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  UtmCoordinateFfi sse_decode_utm_coordinate_ffi(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_zone = sse_decode_u_8(deserializer);
    var var_hemisphere = sse_decode_cardinal_direction(deserializer);
    var var_easting = sse_decode_f_64(deserializer);
    var var_northing = sse_decode_f_64(deserializer);
    return UtmCoordinateFfi(
        zone: var_zone,
        hemisphere: var_hemisphere,
        easting: var_easting,
        northing: var_northing);
  }

  @protected
  ZipExtractor sse_decode_zip_extractor(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_archivePath = sse_decode_String(deserializer);
    var var_outputDir = sse_decode_String(deserializer);
    return ZipExtractor(archivePath: var_archivePath, outputDir: var_outputDir);
  }

  @protected
  ZipWriter sse_decode_zip_writer(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_parentDir = sse_decode_String(deserializer);
    var var_altParentDir = sse_decode_opt_String(deserializer);
    var var_files = sse_decode_list_String(deserializer);
    var var_outputPath = sse_decode_String(deserializer);
    return ZipWriter(
        parentDir: var_parentDir,
        altParentDir: var_altParentDir,
        files: var_files,
        outputPath: var_outputPath);
  }

  @protected
  void sse_encode_Map_String_String_None(
      Map<String, String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_record_string_string(
        self.entries.map((e) => (e.key, e.value)).toList(), serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_config_export_preset(
      ConfigExportPreset self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_config_export_preset(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_record_reader(
      RecordReader self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_record_reader(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_record_writer(
      RecordWriter self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_record_writer(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_zip_extractor(
      ZipExtractor self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_zip_extractor(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_zip_writer(
      ZipWriter self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_zip_writer(self, serializer);
  }

  @protected
  void sse_encode_cardinal_direction(
      CardinalDirection self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_config_combined_field(
      ConfigCombinedField self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.fieldId, serializer);
    sse_encode_list_String(self.fields, serializer);
  }

  @protected
  void sse_encode_config_export_preset(
      ConfigExportPreset self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Map_String_String_None(self.fields, serializer);
    sse_encode_list_config_combined_field(self.combinedFields, serializer);
  }

  @protected
  void sse_encode_config_preset_entry(
      ConfigPresetEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_config_export_preset(self.preset, serializer);
  }

  @protected
  void sse_encode_ddm_coordinate_ffi(
      DdmCoordinateFfi self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.degrees, serializer);
    sse_encode_f_64(self.minutes, serializer);
    sse_encode_cardinal_direction(self.direction, serializer);
  }

  @protected
  void sse_encode_dms_coordinate_ffi(
      DmsCoordinateFfi self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.degrees, serializer);
    sse_encode_u_32(self.minutes, serializer);
    sse_encode_f_64(self.seconds, serializer);
    sse_encode_cardinal_direction(self.direction, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_config_combined_field(
      List<ConfigCombinedField> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_config_combined_field(item, serializer);
    }
  }

  @protected
  void sse_encode_list_config_preset_entry(
      List<ConfigPresetEntry> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_config_preset_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_String(
      List<List<String>> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_prim_u_8_strict(
      List<Uint8List> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_prim_u_8_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_string_string(
      List<(String, String)> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_string(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_config_export_preset(
      ConfigExportPreset? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_config_export_preset(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_String(
      List<String>? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_String(self, serializer);
    }
  }

  @protected
  void sse_encode_record_f_64_f_64(
      (double, double) self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.$1, serializer);
    sse_encode_f_64(self.$2, serializer);
  }

  @protected
  void sse_encode_record_reader(RecordReader self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.filePath, serializer);
  }

  @protected
  void sse_encode_record_string_string(
      (String, String) self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_record_writer(RecordWriter self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.jsonContent, serializer);
    sse_encode_String(self.outputPath, serializer);
    sse_encode_list_String(self.columnNames, serializer);
    sse_encode_String(self.exportFormat, serializer);
    sse_encode_bool(self.concatenateMultiEntries, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_utm_coordinate_ffi(
      UtmCoordinateFfi self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self.zone, serializer);
    sse_encode_cardinal_direction(self.hemisphere, serializer);
    sse_encode_f_64(self.easting, serializer);
    sse_encode_f_64(self.northing, serializer);
  }

  @protected
  void sse_encode_zip_extractor(ZipExtractor self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.archivePath, serializer);
    sse_encode_String(self.outputDir, serializer);
  }

  @protected
  void sse_encode_zip_writer(ZipWriter self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.parentDir, serializer);
    sse_encode_opt_String(self.altParentDir, serializer);
    sse_encode_list_String(self.files, serializer);
    sse_encode_String(self.outputPath, serializer);
  }
}
