[package]
name = "rust_lib_nahpu"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.12.0"
nahpu_archive = { version = "0.1.0", path = "../../../Rust/nahpu_api/crates/nahpu_archive" }
nahpu_db = { version = "0.2.0", path = "../../../Rust/nahpu_api/crates/nahpu_db" }
nahpu_gis = { version = "0.1.0", path = "../../../Rust/nahpu_api/crates/nahpu_gis" }
serde_json = "1.0.150"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
