// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Initializes the configuration database at the specified path.
Future<void> initConfigDb({required String path}) =>
    RustLib.instance.api.crateApiConfigInitConfigDb(path: path);

/// Sets a user config list.
Future<void> setUserConfigList(
        {required String key, required List<String> value}) =>
    RustLib.instance.api
        .crateApiConfigSetUserConfigList(key: key, value: value);

/// Retrieves a user config list.
Future<List<String>?> getUserConfigList({required String key}) =>
    RustLib.instance.api.crateApiConfigGetUserConfigList(key: key);

/// Sets a user config string.
Future<void> setUserConfigString(
        {required String key, required String value}) =>
    RustLib.instance.api
        .crateApiConfigSetUserConfigString(key: key, value: value);

/// Retrieves a user config string.
Future<String?> getUserConfigString({required String key}) =>
    RustLib.instance.api.crateApiConfigGetUserConfigString(key: key);

/// Deletes a user config key.
Future<void> deleteUserConfig({required String key}) =>
    RustLib.instance.api.crateApiConfigDeleteUserConfig(key: key);

/// Saves a record export preset.
Future<void> setRecordExportPreset(
        {required String name, required ConfigExportPreset preset}) =>
    RustLib.instance.api
        .crateApiConfigSetRecordExportPreset(name: name, preset: preset);

/// Retrieves a record export preset.
Future<ConfigExportPreset?> getRecordExportPreset({required String name}) =>
    RustLib.instance.api.crateApiConfigGetRecordExportPreset(name: name);

/// Deletes a record export preset.
Future<void> deleteRecordExportPreset({required String name}) =>
    RustLib.instance.api.crateApiConfigDeleteRecordExportPreset(name: name);

/// Retrieves all record export presets.
Future<List<ConfigPresetEntry>> getAllRecordExportPresets() =>
    RustLib.instance.api.crateApiConfigGetAllRecordExportPresets();

/// Exports all user configs and document presets to a file in either JSON or JSON Lines format.
Future<void> exportConfigToFile(
        {required String filePath, required bool isJson}) =>
    RustLib.instance.api
        .crateApiConfigExportConfigToFile(filePath: filePath, isJson: isJson);

/// Imports and replaces all user configs and document presets from a file.
Future<void> importConfigFromFile({required String filePath}) =>
    RustLib.instance.api.crateApiConfigImportConfigFromFile(filePath: filePath);

/// Saves a template preset JSON string to the config database.
Future<void> setTemplatePreset({required String name, required String value}) =>
    RustLib.instance.api
        .crateApiConfigSetTemplatePreset(name: name, value: value);

/// Retrieves a saved template preset as a JSON string.
Future<String?> getTemplatePreset({required String name}) =>
    RustLib.instance.api.crateApiConfigGetTemplatePreset(name: name);

/// Deletes a template preset.
Future<void> deleteTemplatePreset({required String name}) =>
    RustLib.instance.api.crateApiConfigDeleteTemplatePreset(name: name);

/// Lists all template preset names stored in the database.
Future<List<String>> listTemplatePresets() =>
    RustLib.instance.api.crateApiConfigListTemplatePresets();

/// Exports a single template preset to a file at the specified path.
Future<void> exportTemplatePresetToFile(
        {required String name, required String filePath}) =>
    RustLib.instance.api.crateApiConfigExportTemplatePresetToFile(
        name: name, filePath: filePath);

/// Saves a document layout.
Future<void> setDocumentLayout(
        {required String name, required DocumentLayoutPreset layout}) =>
    RustLib.instance.api
        .crateApiConfigSetDocumentLayout(name: name, layout: layout);

/// Retrieves a document layout.
Future<DocumentLayoutPreset?> getDocumentLayout({required String name}) =>
    RustLib.instance.api.crateApiConfigGetDocumentLayout(name: name);

/// Deletes a document layout.
Future<void> deleteDocumentLayout({required String name}) =>
    RustLib.instance.api.crateApiConfigDeleteDocumentLayout(name: name);

/// Retrieves all document layouts.
Future<List<DocumentLayoutPreset>> getAllDocumentLayouts() =>
    RustLib.instance.api.crateApiConfigGetAllDocumentLayouts();

/// Represents a combined export field configuration.
class ConfigCombinedField {
  /// Unique identifier for the combined field.
  final String fieldId;

  /// List of field names that are combined.
  final List<String> fields;

  const ConfigCombinedField({
    required this.fieldId,
    required this.fields,
  });

  @override
  int get hashCode => fieldId.hashCode ^ fields.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConfigCombinedField &&
          runtimeType == other.runtimeType &&
          fieldId == other.fieldId &&
          fields == other.fields;
}

/// Represents an export preset containing field maps and combined fields.
class ConfigExportPreset {
  /// Map of standard field keys to their export names.
  final Map<String, String> fields;

  /// List of fields that are combined during export.
  final List<ConfigCombinedField> combinedFields;

  const ConfigExportPreset({
    required this.fields,
    required this.combinedFields,
  });

  @override
  int get hashCode => fields.hashCode ^ combinedFields.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConfigExportPreset &&
          runtimeType == other.runtimeType &&
          fields == other.fields &&
          combinedFields == other.combinedFields;
}

/// Represents a single preset entry.
class ConfigPresetEntry {
  /// Name of the preset.
  final String name;

  /// Preset details.
  final ConfigExportPreset preset;

  const ConfigPresetEntry({
    required this.name,
    required this.preset,
  });

  @override
  int get hashCode => name.hashCode ^ preset.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConfigPresetEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          preset == other.preset;
}

/// Represents a layout block within a document.
class DocumentLayoutBlock {
  final String templateName;
  final int templateCount;
  final int rows;
  final int cols;
  final double templatePadTopMm;
  final double templatePadLeftMm;
  final double templatePadRightMm;
  final double templatePadBottomMm;
  final bool pageBreakAfter;

  const DocumentLayoutBlock({
    required this.templateName,
    required this.templateCount,
    required this.rows,
    required this.cols,
    required this.templatePadTopMm,
    required this.templatePadLeftMm,
    required this.templatePadRightMm,
    required this.templatePadBottomMm,
    required this.pageBreakAfter,
  });

  @override
  int get hashCode =>
      templateName.hashCode ^
      templateCount.hashCode ^
      rows.hashCode ^
      cols.hashCode ^
      templatePadTopMm.hashCode ^
      templatePadLeftMm.hashCode ^
      templatePadRightMm.hashCode ^
      templatePadBottomMm.hashCode ^
      pageBreakAfter.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DocumentLayoutBlock &&
          runtimeType == other.runtimeType &&
          templateName == other.templateName &&
          templateCount == other.templateCount &&
          rows == other.rows &&
          cols == other.cols &&
          templatePadTopMm == other.templatePadTopMm &&
          templatePadLeftMm == other.templatePadLeftMm &&
          templatePadRightMm == other.templatePadRightMm &&
          templatePadBottomMm == other.templatePadBottomMm &&
          pageBreakAfter == other.pageBreakAfter;
}

/// Represents the overall configuration for document layouts.
class DocumentLayoutPreset {
  final String name;
  final String layoutType;
  final String pageSizeKey;
  final String pageOrientation;
  final double? customPageWidthMm;
  final double? customPageHeightMm;
  final double pagePadTopMm;
  final double pagePadLeftMm;
  final double pagePadRightMm;
  final double pagePadBottomMm;
  final List<DocumentLayoutBlock> blocks;

  const DocumentLayoutPreset({
    required this.name,
    required this.layoutType,
    required this.pageSizeKey,
    required this.pageOrientation,
    this.customPageWidthMm,
    this.customPageHeightMm,
    required this.pagePadTopMm,
    required this.pagePadLeftMm,
    required this.pagePadRightMm,
    required this.pagePadBottomMm,
    required this.blocks,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      layoutType.hashCode ^
      pageSizeKey.hashCode ^
      pageOrientation.hashCode ^
      customPageWidthMm.hashCode ^
      customPageHeightMm.hashCode ^
      pagePadTopMm.hashCode ^
      pagePadLeftMm.hashCode ^
      pagePadRightMm.hashCode ^
      pagePadBottomMm.hashCode ^
      blocks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DocumentLayoutPreset &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          layoutType == other.layoutType &&
          pageSizeKey == other.pageSizeKey &&
          pageOrientation == other.pageOrientation &&
          customPageWidthMm == other.customPageWidthMm &&
          customPageHeightMm == other.customPageHeightMm &&
          pagePadTopMm == other.pagePadTopMm &&
          pagePadLeftMm == other.pagePadLeftMm &&
          pagePadRightMm == other.pagePadRightMm &&
          pagePadBottomMm == other.pagePadBottomMm &&
          blocks == other.blocks;
}
