// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`, `from`, `from`

/// Initializes the configuration database at the specified path.
Future<void> initConfigDb({required String path}) =>
    RustLib.instance.api.crateApiConfigInitConfigDb(path: path);

/// Sets a user config list.
Future<void> setUserConfigList(
        {required String key, required List<String> value}) =>
    RustLib.instance.api
        .crateApiConfigSetUserConfigList(key: key, value: value);

/// Retrieves a user config list.
Future<List<String>?> getUserConfigList({required String key}) =>
    RustLib.instance.api.crateApiConfigGetUserConfigList(key: key);

/// Sets a user config string.
Future<void> setUserConfigString(
        {required String key, required String value}) =>
    RustLib.instance.api
        .crateApiConfigSetUserConfigString(key: key, value: value);

/// Retrieves a user config string.
Future<String?> getUserConfigString({required String key}) =>
    RustLib.instance.api.crateApiConfigGetUserConfigString(key: key);

/// Deletes a user config key.
Future<void> deleteUserConfig({required String key}) =>
    RustLib.instance.api.crateApiConfigDeleteUserConfig(key: key);

/// Saves a document export preset.
Future<void> setDocumentPreset(
        {required String name, required ConfigExportPreset preset}) =>
    RustLib.instance.api
        .crateApiConfigSetDocumentPreset(name: name, preset: preset);

/// Retrieves a document export preset.
Future<ConfigExportPreset?> getDocumentPreset({required String name}) =>
    RustLib.instance.api.crateApiConfigGetDocumentPreset(name: name);

/// Deletes a document export preset.
Future<void> deleteDocumentPreset({required String name}) =>
    RustLib.instance.api.crateApiConfigDeleteDocumentPreset(name: name);

/// Retrieves all document export presets.
Future<List<ConfigPresetEntry>> getAllDocumentPresets() =>
    RustLib.instance.api.crateApiConfigGetAllDocumentPresets();

/// Exports all user configs and document presets to a file in either JSON or KDL format.
Future<void> exportConfigToFile(
        {required String filePath, required bool isJson}) =>
    RustLib.instance.api
        .crateApiConfigExportConfigToFile(filePath: filePath, isJson: isJson);

/// Imports and replaces all user configs and document presets from a file.
Future<void> importConfigFromFile({required String filePath}) =>
    RustLib.instance.api.crateApiConfigImportConfigFromFile(filePath: filePath);

/// Represents a combined export field configuration.
class ConfigCombinedField {
  /// Unique identifier for the combined field.
  final String fieldId;

  /// List of field names that are combined.
  final List<String> fields;

  const ConfigCombinedField({
    required this.fieldId,
    required this.fields,
  });

  @override
  int get hashCode => fieldId.hashCode ^ fields.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConfigCombinedField &&
          runtimeType == other.runtimeType &&
          fieldId == other.fieldId &&
          fields == other.fields;
}

/// Represents an export preset containing field maps and combined fields.
class ConfigExportPreset {
  /// Map of standard field keys to their export names.
  final Map<String, String> fields;

  /// List of fields that are combined during export.
  final List<ConfigCombinedField> combinedFields;

  const ConfigExportPreset({
    required this.fields,
    required this.combinedFields,
  });

  @override
  int get hashCode => fields.hashCode ^ combinedFields.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConfigExportPreset &&
          runtimeType == other.runtimeType &&
          fields == other.fields &&
          combinedFields == other.combinedFields;
}

/// Represents a single preset entry.
class ConfigPresetEntry {
  /// Name of the preset.
  final String name;

  /// Preset details.
  final ConfigExportPreset preset;

  const ConfigPresetEntry({
    required this.name,
    required this.preset,
  });

  @override
  int get hashCode => name.hashCode ^ preset.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConfigPresetEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          preset == other.preset;
}
