// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Resolves a batch of NAHPU source keys to Darwin Core or Dublin Core terms.
///
/// Unmapped and malformed source keys are intentionally omitted. The caller
/// uses those omissions to generate the corresponding NAHPU namespace header.
Future<List<DwcHeader>> getDwcHeaders({required List<String> sourceKeys}) =>
    RustLib.instance.api.crateApiDwcGetDwcHeaders(sourceKeys: sourceKeys);

/// A resolved Darwin Core header for one NAHPU `table::field` source key.
class DwcHeader {
  final String sourceKey;

  /// The first visible header, retained for compatibility with callers that
  /// only support direct mappings.
  final String header;

  /// All visible headers emitted for this source, in tabular order.
  final List<String> headers;

  /// Static MeasurementOrFact values, when this source is a measurement.
  final String? measurementType;
  final String? measurementUnit;

  const DwcHeader({
    required this.sourceKey,
    required this.header,
    required this.headers,
    this.measurementType,
    this.measurementUnit,
  });

  @override
  int get hashCode =>
      sourceKey.hashCode ^
      header.hashCode ^
      headers.hashCode ^
      measurementType.hashCode ^
      measurementUnit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DwcHeader &&
          runtimeType == other.runtimeType &&
          sourceKey == other.sourceKey &&
          header == other.header &&
          headers == other.headers &&
          measurementType == other.measurementType &&
          measurementUnit == other.measurementUnit;
}
