// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class RecordWriter {
  /// JSON string containing the records to be exported.
  final String jsonContent;

  /// The path to the output file where the records will be written.
  final String outputPath;

  /// The column names to be included in the export.
  final List<String> columnNames;

  /// Export format, e.g., "csv", "json", "excel".
  final String exportFormat;

  const RecordWriter({
    required this.jsonContent,
    required this.outputPath,
    required this.columnNames,
    required this.exportFormat,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<RecordWriter> newInstance(
          {required String jsonContent,
          required String outputPath,
          required List<String> columnNames,
          required String exportFormat}) =>
      RustLib.instance.api.crateApiExportRecordWriterNew(
          jsonContent: jsonContent,
          outputPath: outputPath,
          columnNames: columnNames,
          exportFormat: exportFormat);

  Future<void> write() => RustLib.instance.api.crateApiExportRecordWriterWrite(
        that: this,
      );

  @override
  int get hashCode =>
      jsonContent.hashCode ^
      outputPath.hashCode ^
      columnNames.hashCode ^
      exportFormat.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecordWriter &&
          runtimeType == other.runtimeType &&
          jsonContent == other.jsonContent &&
          outputPath == other.outputPath &&
          columnNames == other.columnNames &&
          exportFormat == other.exportFormat;
}
