// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`

/// Converts DMS to decimal degrees.
///
/// # Examples
///
/// ```
/// use rust_lib_nahpu::api::gis::{dms_to_dd, CardinalDirection};
///
/// let dd = dms_to_dd(41, 24, 12.2, CardinalDirection::North);
/// assert!((dd - 41.40338888888889).abs() < 1e-9);
/// ```
Future<double> dmsToDd(
        {required int degrees,
        required int minutes,
        required double seconds,
        required CardinalDirection direction}) =>
    RustLib.instance.api.crateApiGisDmsToDd(
        degrees: degrees,
        minutes: minutes,
        seconds: seconds,
        direction: direction);

/// Converts DDM to decimal degrees.
///
/// # Examples
///
/// ```
/// use rust_lib_nahpu::api::gis::{ddm_to_dd, CardinalDirection};
///
/// let dd = ddm_to_dd(41, 24.2028, CardinalDirection::North);
/// assert!((dd - 41.40338).abs() < 1e-9);
/// ```
Future<double> ddmToDd(
        {required int degrees,
        required double minutes,
        required CardinalDirection direction}) =>
    RustLib.instance.api.crateApiGisDdmToDd(
        degrees: degrees, minutes: minutes, direction: direction);

/// Converts UTM to decimal degrees latitude and longitude.
Future<(double, double)> utmToDd(
        {required int zone,
        required CardinalDirection hemisphere,
        required double easting,
        required double northing}) =>
    RustLib.instance.api.crateApiGisUtmToDd(
        zone: zone,
        hemisphere: hemisphere,
        easting: easting,
        northing: northing);

/// Converts decimal degrees to DMS.
Future<DmsCoordinateFfi> ddToDms(
        {required double dd, required bool isLatitude}) =>
    RustLib.instance.api.crateApiGisDdToDms(dd: dd, isLatitude: isLatitude);

/// Converts decimal degrees to DDM.
Future<DdmCoordinateFfi> ddToDdm(
        {required double dd, required bool isLatitude}) =>
    RustLib.instance.api.crateApiGisDdToDdm(dd: dd, isLatitude: isLatitude);

/// Converts decimal degrees latitude and longitude to UTM.
Future<UtmCoordinateFfi> ddToUtm(
        {required double latitude, required double longitude}) =>
    RustLib.instance.api
        .crateApiGisDdToUtm(latitude: latitude, longitude: longitude);

/// Automatically detects the coordinate format of a string and parses it to decimal degrees.
Future<double> parseCoordinateString({required String s}) =>
    RustLib.instance.api.crateApiGisParseCoordinateString(s: s);

/// Represents a geographic cardinal direction.
enum CardinalDirection {
  /// Northern hemisphere (positive latitude)
  north,

  /// Southern hemisphere (negative latitude)
  south,

  /// Eastern hemisphere (positive longitude)
  east,

  /// Western hemisphere (negative longitude)
  west,
  ;
}

/// Represents a coordinate in Degrees and Decimal Minutes (DDM) format.
class DdmCoordinateFfi {
  /// Degree component.
  final int degrees;

  /// Minute component.
  final double minutes;

  /// Cardinal direction.
  final CardinalDirection direction;

  const DdmCoordinateFfi({
    required this.degrees,
    required this.minutes,
    required this.direction,
  });

  @override
  int get hashCode => degrees.hashCode ^ minutes.hashCode ^ direction.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DdmCoordinateFfi &&
          runtimeType == other.runtimeType &&
          degrees == other.degrees &&
          minutes == other.minutes &&
          direction == other.direction;
}

/// Represents a coordinate in Degrees, Minutes, and Seconds (DMS) format.
class DmsCoordinateFfi {
  /// Degree component.
  final int degrees;

  /// Minute component.
  final int minutes;

  /// Second component.
  final double seconds;

  /// Cardinal direction.
  final CardinalDirection direction;

  const DmsCoordinateFfi({
    required this.degrees,
    required this.minutes,
    required this.seconds,
    required this.direction,
  });

  @override
  int get hashCode =>
      degrees.hashCode ^
      minutes.hashCode ^
      seconds.hashCode ^
      direction.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DmsCoordinateFfi &&
          runtimeType == other.runtimeType &&
          degrees == other.degrees &&
          minutes == other.minutes &&
          seconds == other.seconds &&
          direction == other.direction;
}

/// Represents a coordinate in Universal Transverse Mercator (UTM) format.
class UtmCoordinateFfi {
  /// UTM Zone number.
  final int zone;

  /// UTM Hemisphere (North or South).
  final CardinalDirection hemisphere;

  /// Easting in meters.
  final double easting;

  /// Northing in meters.
  final double northing;

  const UtmCoordinateFfi({
    required this.zone,
    required this.hemisphere,
    required this.easting,
    required this.northing,
  });

  @override
  int get hashCode =>
      zone.hashCode ^
      hemisphere.hashCode ^
      easting.hashCode ^
      northing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UtmCoordinateFfi &&
          runtimeType == other.runtimeType &&
          zone == other.zone &&
          hemisphere == other.hemisphere &&
          easting == other.easting &&
          northing == other.northing;
}
