// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `from`, `from`, `from`, `from`, `try_from`

/// Exports one or more coordinates using NAHPU GIS.
Future<void> exportCoordinates({
  required List<CoordinateTransferRecord> coordinates,
  required CoordinateExportFormat format,
  required String outputPath,
}) => RustLib.instance.api.crateApiGisExportCoordinates(
  coordinates: coordinates,
  format: format,
  outputPath: outputPath,
);

/// Imports point coordinates from GeoJSON, KML, zipped Shapefile, or GPX.
Future<CoordinateFileImportResult> importCoordinates({
  required String inputPath,
}) => RustLib.instance.api.crateApiGisImportCoordinates(inputPath: inputPath);

/// Converts GeoJSON or a zipped WGS84 Shapefile to normalized GeoJSON.
Future<ImportedVectorLayer> convertVectorLayerToGeojson({
  required String inputPath,
  required String outputPath,
}) => RustLib.instance.api.crateApiGisConvertVectorLayerToGeojson(
  inputPath: inputPath,
  outputPath: outputPath,
);

/// Converts DMS to decimal degrees.
///
/// # Examples
///
/// ```
/// use rust_lib_nahpu::api::gis::{dms_to_dd, CardinalDirection};
///
/// let dd = dms_to_dd(41, 24, 12.2, CardinalDirection::North);
/// assert!((dd - 41.40338888888889).abs() < 1e-9);
/// ```
Future<double> dmsToDd({
  required int degrees,
  required int minutes,
  required double seconds,
  required CardinalDirection direction,
}) => RustLib.instance.api.crateApiGisDmsToDd(
  degrees: degrees,
  minutes: minutes,
  seconds: seconds,
  direction: direction,
);

/// Converts DDM to decimal degrees.
///
/// # Examples
///
/// ```
/// use rust_lib_nahpu::api::gis::{ddm_to_dd, CardinalDirection};
///
/// let dd = ddm_to_dd(41, 24.2028, CardinalDirection::North);
/// assert!((dd - 41.40338).abs() < 1e-9);
/// ```
Future<double> ddmToDd({
  required int degrees,
  required double minutes,
  required CardinalDirection direction,
}) => RustLib.instance.api.crateApiGisDdmToDd(
  degrees: degrees,
  minutes: minutes,
  direction: direction,
);

/// Converts UTM to decimal degrees latitude and longitude.
Future<(double, double)> utmToDd({
  required int zone,
  required CardinalDirection hemisphere,
  required double easting,
  required double northing,
}) => RustLib.instance.api.crateApiGisUtmToDd(
  zone: zone,
  hemisphere: hemisphere,
  easting: easting,
  northing: northing,
);

/// Converts decimal degrees to DMS.
Future<DmsCoordinateFfi> ddToDms({
  required double dd,
  required bool isLatitude,
}) => RustLib.instance.api.crateApiGisDdToDms(dd: dd, isLatitude: isLatitude);

/// Converts decimal degrees to DDM.
Future<DdmCoordinateFfi> ddToDdm({
  required double dd,
  required bool isLatitude,
}) => RustLib.instance.api.crateApiGisDdToDdm(dd: dd, isLatitude: isLatitude);

/// Converts decimal degrees latitude and longitude to UTM.
Future<UtmCoordinateFfi> ddToUtm({
  required double latitude,
  required double longitude,
}) => RustLib.instance.api.crateApiGisDdToUtm(
  latitude: latitude,
  longitude: longitude,
);

/// Automatically detects the coordinate format of a string and parses it to decimal degrees.
Future<double> parseCoordinateString({required String s}) =>
    RustLib.instance.api.crateApiGisParseCoordinateString(s: s);

/// Represents a geographic cardinal direction.
enum CardinalDirection {
  /// Northern hemisphere (positive latitude)
  north,

  /// Southern hemisphere (negative latitude)
  south,

  /// Eastern hemisphere (positive longitude)
  east,

  /// Western hemisphere (negative longitude)
  west,
}

/// File formats supported by the coordinate exporter.
enum CoordinateExportFormat { geoJson, kml, shapefile }

/// Coordinates and diagnostics returned by a file import.
class CoordinateFileImportResult {
  final List<CoordinateTransferRecord> coordinates;
  final BigInt skippedCount;
  final List<String> warnings;

  const CoordinateFileImportResult({
    required this.coordinates,
    required this.skippedCount,
    required this.warnings,
  });

  @override
  int get hashCode =>
      coordinates.hashCode ^ skippedCount.hashCode ^ warnings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoordinateFileImportResult &&
          runtimeType == other.runtimeType &&
          coordinates == other.coordinates &&
          skippedCount == other.skippedCount &&
          warnings == other.warnings;
}

/// Portable point fields supported by NAHPU GIS imports and exports.
class CoordinateTransferRecord {
  final String nameId;
  final String? notes;
  final double? decimalLongitude;
  final double? decimalLatitude;
  final double? elevationInMeter;

  const CoordinateTransferRecord({
    required this.nameId,
    this.notes,
    this.decimalLongitude,
    this.decimalLatitude,
    this.elevationInMeter,
  });

  @override
  int get hashCode =>
      nameId.hashCode ^
      notes.hashCode ^
      decimalLongitude.hashCode ^
      decimalLatitude.hashCode ^
      elevationInMeter.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoordinateTransferRecord &&
          runtimeType == other.runtimeType &&
          nameId == other.nameId &&
          notes == other.notes &&
          decimalLongitude == other.decimalLongitude &&
          decimalLatitude == other.decimalLatitude &&
          elevationInMeter == other.elevationInMeter;
}

/// Represents a coordinate in Degrees and Decimal Minutes (DDM) format.
class DdmCoordinateFfi {
  /// Degree component.
  final int degrees;

  /// Minute component.
  final double minutes;

  /// Cardinal direction.
  final CardinalDirection direction;

  const DdmCoordinateFfi({
    required this.degrees,
    required this.minutes,
    required this.direction,
  });

  @override
  int get hashCode => degrees.hashCode ^ minutes.hashCode ^ direction.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DdmCoordinateFfi &&
          runtimeType == other.runtimeType &&
          degrees == other.degrees &&
          minutes == other.minutes &&
          direction == other.direction;
}

/// Represents a coordinate in Degrees, Minutes, and Seconds (DMS) format.
class DmsCoordinateFfi {
  /// Degree component.
  final int degrees;

  /// Minute component.
  final int minutes;

  /// Second component.
  final double seconds;

  /// Cardinal direction.
  final CardinalDirection direction;

  const DmsCoordinateFfi({
    required this.degrees,
    required this.minutes,
    required this.seconds,
    required this.direction,
  });

  @override
  int get hashCode =>
      degrees.hashCode ^
      minutes.hashCode ^
      seconds.hashCode ^
      direction.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DmsCoordinateFfi &&
          runtimeType == other.runtimeType &&
          degrees == other.degrees &&
          minutes == other.minutes &&
          seconds == other.seconds &&
          direction == other.direction;
}

/// Metadata for a user vector layer normalized by `nahpu_gis`.
class ImportedVectorLayer {
  /// Number of GeoJSON features written.
  final BigInt featureCount;

  /// WGS84 bounds in west, south, east, north order.
  final Float64List? bounds;

  /// Coordinate reference system of the output.
  final String sourceCrs;

  const ImportedVectorLayer({
    required this.featureCount,
    this.bounds,
    required this.sourceCrs,
  });

  @override
  int get hashCode =>
      featureCount.hashCode ^ bounds.hashCode ^ sourceCrs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportedVectorLayer &&
          runtimeType == other.runtimeType &&
          featureCount == other.featureCount &&
          bounds == other.bounds &&
          sourceCrs == other.sourceCrs;
}

/// Represents a coordinate in Universal Transverse Mercator (UTM) format.
class UtmCoordinateFfi {
  /// UTM Zone number.
  final int zone;

  /// UTM Hemisphere (North or South).
  final CardinalDirection hemisphere;

  /// Easting in meters.
  final double easting;

  /// Northing in meters.
  final double northing;

  const UtmCoordinateFfi({
    required this.zone,
    required this.hemisphere,
    required this.easting,
    required this.northing,
  });

  @override
  int get hashCode =>
      zone.hashCode ^
      hemisphere.hashCode ^
      easting.hashCode ^
      northing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UtmCoordinateFfi &&
          runtimeType == other.runtimeType &&
          zone == other.zone &&
          hemisphere == other.hemisphere &&
          easting == other.easting &&
          northing == other.northing;
}
