// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `from`, `from`

/// Inspects a static JPEG, PNG, or WebP without re-encoding it.
Future<ImageSourceInfo> inspectImage({required String inputPath}) =>
    RustLib.instance.api.crateApiImagesInspectImage(inputPath: inputPath);

/// Converts and optionally resizes a static image into a new file.
Future<ImageExportResult> exportImage({
  required String inputPath,
  required String outputPath,
  required ImageExportFormat outputFormat,
  int? resizeWidth,
  int? resizeHeight,
  required int jpegQuality,
}) => RustLib.instance.api.crateApiImagesExportImage(
  inputPath: inputPath,
  outputPath: outputPath,
  outputFormat: outputFormat,
  resizeWidth: resizeWidth,
  resizeHeight: resizeHeight,
  jpegQuality: jpegQuality,
);

/// Static image formats supported for conversion and export.
enum ImageExportFormat { jpeg, png, webP }

/// Properties of a completed image export.
class ImageExportResult {
  final int width;
  final int height;
  final BigInt bytes;
  final bool resized;

  const ImageExportResult({
    required this.width,
    required this.height,
    required this.bytes,
    required this.resized,
  });

  @override
  int get hashCode =>
      width.hashCode ^ height.hashCode ^ bytes.hashCode ^ resized.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageExportResult &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          bytes == other.bytes &&
          resized == other.resized;
}

/// Source properties needed to present aspect-locked resize controls.
class ImageSourceInfo {
  final ImageExportFormat format;
  final int width;
  final int height;

  const ImageSourceInfo({
    required this.format,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode => format.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageSourceInfo &&
          runtimeType == other.runtimeType &&
          format == other.format &&
          width == other.width &&
          height == other.height;
}
