import 'package:flutter/foundation.dart';
import 'dart:math' as math;
import 'dart:io';
import 'package:nahpu/services/io_services.dart';
import 'package:nahpu/services/export/common.dart';

import 'package:flutter/services.dart' show rootBundle, AssetManifest;
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:nahpu/screens/templates/template_model.dart';
import 'package:nahpu/services/database/database.dart';
import 'package:nahpu/services/template_service.dart';
import 'package:nahpu/services/template_settings_services.dart';
import 'package:nahpu/services/providers/database.dart';
import 'package:nahpu/services/export/dynamic_record_exporter.dart';
import 'package:nahpu/services/collevent_services.dart';
import 'package:nahpu/services/personnel_services.dart';
import 'package:nahpu/services/project_services.dart';
import 'package:nahpu/services/export/site_writer.dart';
import 'package:nahpu/services/export/narrative_writer.dart';
import 'package:nahpu/services/narrative_services.dart';
import 'package:nahpu/services/site_services.dart';
import 'package:nahpu/services/specimen_services.dart';
import 'package:nahpu/services/providers/document_selection.dart';
import 'package:nahpu/services/providers/projects.dart';
import 'package:nahpu/services/types/export.dart';
import 'package:nahpu/src/rust/api/export.dart' as rust_export;
import 'package:nahpu/src/rust/api/config.dart' as rust_config;
import 'package:path/path.dart' as path;
import 'package:qr/qr.dart';

part 'document_writer/layout_options.dart';
part 'document_writer/placeholder.dart';
part 'document_writer/continuous_print_item.dart';
part 'document_writer/field_values.dart';
part 'document_writer/page_geometry.dart';
part 'document_writer/font_loader.dart';
part 'document_writer/layout_record_collector.dart';
part 'document_writer/template_substitutor.dart';
part 'document_writer/typst_renderer.dart';
part 'document_writer/pdf_builder.dart';
part 'document_writer/writer.dart';
