import 'package:flutter/foundation.dart';
import 'dart:math' as math;
import 'dart:io';
import 'package:nahpu/services/common/io_services.dart';
import 'package:nahpu/services/custom_fields/custom_field_service.dart';
import 'package:nahpu/services/export/common.dart';

import 'package:flutter/services.dart' show rootBundle, AssetManifest;
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:nahpu/services/specimens/conditional_brackets.dart';
import 'package:nahpu/services/export/text_replacements.dart';
import 'package:nahpu/screens/templates/template_model.dart';
import 'package:nahpu/services/database/database.dart';
import 'package:nahpu/services/database/specimen_queries.dart';
import 'package:nahpu/services/templates/document_layout_service.dart';
import 'package:nahpu/services/templates/template_service.dart';
import 'package:nahpu/services/templates/nested_list_service.dart';
import 'package:nahpu/services/templates/dynamic_layout_service.dart';
import 'package:nahpu/services/providers/database.dart';
import 'package:nahpu/services/export/dynamic_record_exporter.dart';
import 'package:nahpu/services/events/collevent_services.dart';
import 'package:nahpu/services/projects/personnel_services.dart';
import 'package:nahpu/services/projects/project_services.dart';
import 'package:nahpu/services/export/site_writer.dart';
import 'package:nahpu/services/export/narrative_writer.dart';
import 'package:nahpu/services/narrative/narrative_services.dart';
import 'package:nahpu/services/sites/site_services.dart';
import 'package:nahpu/services/specimens/specimen_services.dart';
import 'package:nahpu/services/providers/document_selection.dart';
import 'package:nahpu/services/providers/projects.dart';
import 'package:nahpu/services/types/export.dart';
import 'package:nahpu/services/types/specimens.dart';
import 'package:nahpu/services/types/custom_field.dart';
import 'package:nahpu/src/rust/api/document.dart' as rust_document;
import 'package:nahpu/src/rust/api/config.dart' as rust_config;
import 'package:path/path.dart' as path;
import 'package:qr/qr.dart';

part 'document_writer/layout_options.dart';
part 'document_writer/placeholder.dart';
part 'document_writer/continuous_print_item.dart';
part 'document_writer/field_values.dart';
part 'document_writer/page_geometry.dart';
part 'document_writer/font_loader.dart';
part 'document_writer/layout_record_collector.dart';
part 'document_writer/template_substitutor.dart';
part 'document_writer/typst_renderer.dart';
part 'document_writer/pdf_build_models.dart';
part 'document_writer/record_sorter.dart';
part 'document_writer/pdf_layout_metrics.dart';
part 'document_writer/pdf_input_resolver.dart';
part 'document_writer/pdf_continuous_planner.dart';
part 'document_writer/pdf_sheet_pagination.dart';
part 'document_writer/pdf_sheet_planner.dart';
part 'document_writer/pdf_composer.dart';
part 'document_writer/pdf_builder.dart';
part 'document_writer/writer.dart';
